//
// Created by potato_coder on 04.12.22.
//

#ifndef SYNTACORE_TOOLS_INTERN_TASK_APP_STATUS_H
#define SYNTACORE_TOOLS_INTERN_TASK_APP_STATUS_H

enum file_actions_status{
    FILE_OPEN_OK = 0,
    FILE_OPEN_ERROR = 1,
    FILE_CLOSE_OK = 2,
    FILE_CLOSE_ERROR = 3,
    FILE_READ_OK = 4,
    FILE_READ_ERROR = 5,
    FILE_WRITE_OK = 6,
    FILE_WRITE_ERROR = 7
};

#endif //SYNTACORE_TOOLS_INTERN_TASK_APP_STATUS_H
