//
// Created by potato_coder on 04.12.22.
//

#ifndef SYNTACORE_TOOLS_INTERN_TASK_IO_STREAM_HANDLER_H
#define SYNTACORE_TOOLS_INTERN_TASK_IO_STREAM_HANDLER_H

#endif //SYNTACORE_TOOLS_INTERN_TASK_IO_STREAM_HANDLER_H
